### ISSUE TITLE
use purl-fetcher instead of dor-fetcher

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/base_indexer#24]
NOTE:  do not work on this without talking to @lmcglohon  and/or @atz  -- there are tendrils...

https://github.com/sul-dlss/base_indexer/blob/master/app/controllers/base_indexer/collections_controller.rb#L15-16:

```ruby
      # initialize dor-fetcher to get list of druids for this collection
      df = DorFetcher::Client.new(service_url: Rails.application.config.dor_fetcher_url)
```

and  https://github.com/sul-dlss/base_indexer/blob/master/lib/tasks/index.rake#L165 

```
df = DorFetcher::Client.new({:service_url => Rails.application.config.dor_fetcher_url})
```

or, if this is unused code, get rid of it.

**Comment by lmcglohon** [comment]
Handled by https://github.com/sul-dlss/base_indexer/pull/30
