### ISSUE TITLE
add app_name and app_version to the documentation

### ISSUE THREAD

**Issue by aalsum** [sul-dlss/base_indexer#4]
config.app_version = "0.0"
config.app_name = "[You have to override this name in your app]"

**Comment by lmcglohon** [comment]
@aalsum Is this still an issue?

**Comment by aalsum** [comment]
Yes, we need to add this info the documentation (on wiki here on github). I look to the wiki and I couldn't find it.

**Comment by lmcglohon** [comment]
Fixed in https://github.com/sul-dlss/base_indexer/wiki/Installation, with the engine configuration section.
